version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/backend"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: maven-source-plugin
        versions: [3.3.0]
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"       
        
