services:

  data-provider:
    image: ghcr.io/informatievlaanderen/ldi-orchestrator:20230927142432
    container_name: demonstrator-data-provider
    ports:
      - 8082:8080
    volumes:
      - ./gipod.config.yml:/ldio/application.yml:ro
      - ./rml:/ldio/rml:ro
      - ./sparql:/ldio/sparql:ro
    depends_on:
      rdf4j-server:
        condition: service_healthy
      demonstrator:
        condition: service_started
    networks:
      - demonstrator

  demonstrator:
    container_name: demonstrator
    image: vsds-demonstrator
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./demonstrator.env
    ports:
      - 8084:8080
    depends_on:
      - postgresql
      - rdf4j-server
    networks:
      - demonstrator

  rdf4j-server:
    image: eclipse/rdf4j-workbench:latest
    container_name: demonstrator-rdf4j-server
    environment:
      - "JAVA_OPTS=-Xms1g -Xmx4g"
    ports:
      - 8080:8080
    restart: on-failure
    healthcheck:
      test: "curl --fail http://localhost:8080/rdf4j-workbench/repositories/NONE/repositories || exit 1"
    networks:
      - demonstrator

  postgresql:
    image: kartoza/postgis
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=test
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the five specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
      - RUN_AS_ROOT=true
    ports:
      - "25432:5432"
    restart: on-failure
    healthcheck:
      test: "PGPASSWORD=test pg_isready -h 127.0.0.1 -U postgres -d test"
    networks:
      - demonstrator

networks:
  demonstrator:
    driver: bridge
    name: demonstrator
