version: '3.3'
services:

  ldio-workbench:
    container_name: ${USECASE_NAME:-nifi-less-approach}_ldio-workbench
    image: ldes/ldi-orchestrator:1.2.0
    ports:
      - 8082:8080
    volumes:
      - ./ldio-workbench.config.yml:/ldio/application.yml:ro