server:
  port: 8082
orchestrator:
  pipelines:
    - name: gipod
      input:
        name: be.vlaanderen.informatievlaanderen.ldes.ldi.client.LdioLdesClient
        config:
          url: https://private-api.gipod.vlaanderen.be/api/v1/ldes/mobility-hindrances?generatedAtTime=2023-10-05T10:28:37.923Z
          sourceFormat: application/ld+json
      outputs:
        - name: be.vlaanderen.informatievlaanderen.ldes.ldi.RepositoryMaterialiser
          config:
            sparql-host: http://rdf4j-server:8080/rdf4j-server
            repository-id: test
        - name: be.vlaanderen.informatievlaanderen.ldes.ldio.LdioHttpOut
          config:
            content-type: application/n-quads
            endpoint: http://demonstrator:8080/api/gipod/members
    - name: verkeersmetingen-pipeline
      description: "Simple http in, version creation, http out pipeline allowing to pause output."
      input:
        name: be.vlaanderen.informatievlaanderen.ldes.ldio.LdioHttpInPoller
        config:
          url: http://miv.opendata.belfla.be/miv/verkeersdata
          interval: PT10S
        adapter:
          name: be.vlaanderen.informatievlaanderen.ldes.ldi.RmlAdapter
          config:
            mapping: /ldio/rml/verkeersmetingen.ttl
      transformers:
        - name: be.vlaanderen.informatievlaanderen.ldes.ldi.SparqlConstructTransformer
          config:
            query: /ldio/sparql/meting.to-oslo.rq
        - name: be.vlaanderen.informatievlaanderen.ldes.ldi.VersionObjectCreator
          config:
            member-type: https://data.vlaanderen.be/ns/verkeersmetingen#Verkeersmeting
            delimiter: "/"
            date-observed-property: "<http://def.isotc211.org/iso19156/2011/CountObservation#OM_CountObservation.phenomenonTime>/<http://www.w3.org/2006/time#hasBeginning>/<http://www.w3.org/2006/time#inXSDDateTimeStamp>"
            generatedAt-property: http://www.w3.org/ns/prov#generatedAtTime
            versionOf-property: http://purl.org/dc/terms/isVersionOf
      outputs:
        - name: be.vlaanderen.informatievlaanderen.ldes.ldi.RepositoryMaterialiser
          config:
            sparql-host: http://host.docker.internal:8080/rdf4j-server
            repository-id: test
        - name: be.vlaanderen.informatievlaanderen.ldes.ldio.LdioHttpOut
          config:
            endpoint: http://demonstrator:8080/api/verkeersmeting/members
            content-type: application/n-quads