server:
  port: 8082
orchestrator:
  pipelines:
    - name: gipod
      input:
        name: Ldio:LdesClientConnector
        config:
          url: https://private-api.gipod.vlaanderen.be/api/v1/ldes/mobility-hindrances?generatedAtTime=2024-10-05T10:28:37.923Z
          source-format: application/ld+json
      outputs:
        - name: Ldio:RepositoryMaterialiser
          config:
            sparql-host: http://rdf4j-server:8080/rdf4j-server
            repository-id: test
            named-graph: http://gipod
        - name: Ldio:HttpOut
          config:
            rdf-writer:
              content-type: application/n-quads
            endpoint: http://host.docker.internal:8084/api/gipod/members
    - name: verkeersmetingen-pipeline
      description: "Simple http in, version creation, http out pipeline allowing to pause output."
      input:
        name: Ldio:HttpInPoller
        config:
          url: http://miv.opendata.belfla.be/miv/verkeersdata
          interval: PT10S
        adapter:
          name: Ldio:RmlAdapter
          config:
            mapping: /ldio/rml/verkeersmetingen.ttl
      transformers:
        - name: Ldio:SparqlConstructTransformer
          config:
            query: /ldio/sparql/meting.to-oslo.rq
        - name: Ldio:VersionObjectCreator
          config:
            member-type: https://data.vlaanderen.be/ns/verkeersmetingen#Verkeersmeting
            delimiter: "/"
            date-observed-property: "<http://def.isotc211.org/iso19156/2011/CountObservation#OM_CountObservation.phenomenonTime>/<http://www.w3.org/2006/time#hasBeginning>/<http://www.w3.org/2006/time#inXSDDateTimeStamp>"
            generatedAt-property: http://www.w3.org/ns/prov#generatedAtTime
            versionOf-property: http://purl.org/dc/terms/isVersionOf
      outputs:
        - name: Ldio:RepositoryMaterialiser
          config:
            sparql-host: http://rdf4j-server:8080/rdf4j-server
            repository-id: test
            named-graph: http://verkeersmeting
        - name: Ldio:HttpOut
          config:
            endpoint: http://host.docker.internal:8084/api/verkeersmeting/members
            rdf-writer:
              content-type: application/n-quads
    - name: stations-pipeline
      description: "HTTP polling, OSLO transformation, version creation & HTTP sending."
      input:
        name: Ldio:HttpInPoller
        config:
          url: https://api.blue-bike.be/pub/location
          interval: PT2M
        adapter:
          name: Ldio:RmlAdapter
          config:
            mapping: /ldio/rml/stations.ttl
      outputs:
        - name: Ldio:RepositoryMaterialiser
          config:
            sparql-host: http://rdf4j-server:8080/rdf4j-server
            repository-id: test
            named-graph: http://bluebikes
        - name: Ldio:HttpOut
          config:
            endpoint: http://host.docker.internal:8084/api/bluebikes/members
            rdf-writer:
              content-type: application/n-quads
    - name: crowdscan-observations-pipeline
      input:
        name: Ldio:LdesClientConnector
        config:
          url: https://azure.crowdscan.be/ldes-scewc/observations
      transformers:
        - name: Ldio:SparqlConstructTransformer
          config:
            query: ./sparql/crowdscan.add-query.rq
            infer: true
        - name: Ldio:HttpEnricher
          config:
            url-property-path: https://crowdscan.be/ns/HttpRequest.url
            body-property-path: https://crowdscan.be/ns/HttpRequest.body
            http-method-property-path: https://crowdscan.be/ns/HttpRequest.method
            header-property-path: https://crowdscan.be/ns/HttpRequest.header
            adapter:
              name: Ldio:RdfAdapter
        - name: Ldio:SparqlConstructTransformer
          config:
            query: ./sparql/crowdscan.remove-query.rq
            infer: false
      outputs:
        - name: Ldio:RepositoryMaterialiser
          config:
            sparql-host: http://rdf4j-server:8080/rdf4j-server
            repository-id: test
            named-graph: http://crowdscan
        - name: Ldio:HttpOut
          config:
            endpoint: http://host.docker.internal:8084/api/crowdscan/members
            rdf-writer:
              content-type: application/n-quads
    - name: crowdscan-locations-pipeline
      input:
        name: Ldio:LdesClientConnector
        config:
          url: https://azure.crowdscan.be/ldes-scewc/zones
      outputs:
        - name: Ldio:RepositoryMaterialiser
          config:
            sparql-host: http://rdf4j-server:8080/rdf4j-server
            repository-id: locations
            named-graph: http://crowdscan-locations