spring:
  datasource:
    url: jdbc:postgresql://localhost:25432/test
    username: postgres
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

ldes:
  streams:
    - "https://data.vlaanderen.be/ns/mobiliteit#Mobiliteitshinder"

