spring:
  datasource:
    url: jdbc:postgresql://localhost:25432/test
    username: postgres
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

ldes:
  streams:
    gipod:
      member-type: "https://data.vlaanderen.be/ns/mobiliteit#Mobiliteitshinder"
      timestamp-path: "http://www.w3.org/ns/prov#generatedAtTime"
      property-predicates:
        startTime: "http://data.europa.eu/m8g/startTime"
        endTime: "http://data.europa.eu/m8g/endTime"
    verkeersmeting:
      member-type: "https://data.vlaanderen.be/ns/verkeersmetingen#Verkeersmeting"
      timestamp-path: "http://www.w3.org/ns/prov#generatedAtTime"
      property-predicates:
        fullName: "http://custom/meetpunt#VolledigeNaam"
        countObservationResult: "http://def.isotc211.org/iso19156/2011/CountObservation#OM_CountObservation.result"
graphdb:
  url: "http://localhost:8080/rdf4j-server/repositories/"
  repositoryId: "test"
server:
  port: 8084