spring:
  datasource:
    url: jdbc:postgresql://localhost:25432/test
    username: postgres
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

ldes:
  streams:
    -
      name: Mobility-hindrances
      member-type: "https://data.vlaanderen.be/ns/mobiliteit#Mobiliteitshinder"
      timestamp-path: "http://www.w3.org/ns/prov#generatedAtTime"
graphdb:
  url: "http://localhost:8080/rdf4j-server/repositories/"
  repositoryId: "test"
server:
  port: 8084