server:
  port: 8080
orchestrator:
  pipelines:
    - name: meetpunten-pipeline
      description: "Simple http in, version creation, http out pipeline allowing to pause output."
      input:
        name: be.vlaanderen.informatievlaanderen.ldes.ldio.LdioHttpInPoller
        config:
          url: http://miv.opendata.belfla.be/miv/configuratie/xml
          interval: PT5M
        adapter:
          name: be.vlaanderen.informatievlaanderen.ldes.ldi.RmlAdapter
          config:
            mapping: ./rml/meetpunten.ttl
      transformers:
        - name: be.vlaanderen.informatievlaanderen.ldes.ldi.SparqlConstructTransformer
          config:
            query: ./sparql/fix-decimal-points.rq
        - name: be.vlaanderen.informatievlaanderen.ldes.ldi.SparqlConstructTransformer
          config:
            query: ./sparql/meetpunt-to-oslo.rq
        - name: be.vlaanderen.informatievlaanderen.ldes.ldi.VersionObjectCreator
          config:
            member-type: https://data.vlaanderen.be/ns/verkeersmetingen#Verkeersmeetpunt
            delimiter: "/"
            date-observed-property: http://purl.org/dc/terms/modified
            generatedAt-property: http://www.w3.org/ns/prov#generatedAtTime
            versionOf-property: http://purl.org/dc/terms/isVersionOf
      outputs:
        - name: be.vlaanderen.informatievlaanderen.ldes.ldio.LdioHttpOut
          config:
            endpoint: http://host.docker.internal:3000/data/observation-point
            content-type: application/n-quads

    - name: verkeersmetingen-pipeline
      description: "Simple http in, version creation, http out pipeline allowing to pause output."
      input:
        name: be.vlaanderen.informatievlaanderen.ldes.ldio.LdioHttpInPoller
        config:
          url: http://miv.opendata.belfla.be/miv/verkeersdata
          interval: PT1M
        adapter:
          name: be.vlaanderen.informatievlaanderen.ldes.ldi.RmlAdapter
          config:
            mapping: ./rml/verkeersmetingen.ttl
      transformers:
        - name: be.vlaanderen.informatievlaanderen.ldes.ldi.SparqlConstructTransformer
          config:
            query: ./sparql/meting-to-oslo.rq
        - name: be.vlaanderen.informatievlaanderen.ldes.ldi.VersionObjectCreator
          config:
            # TODO: we have to produce version objects for multiple subjects which are generated by the above sparql construct
            #   but the VersionObjectCreator only expects one subject at the time and the LDES Server does not support bulk ingests
            #   so we need to create a 'simple' splitter component to break down the multiple subjects per message into multiple messages with one subject
            #   to workaround this for now we combine all generated dv:Verkeersmeting into one dv:Verkeersmetingverzameling and version the latter
            #   NOTE: this is obviously WRONG as we do not version the measurements but only their 'container'
            # member-type: https://data.vlaanderen.be/ns/verkeersmetingen#Verkeersmeting
            member-type: https://data.vlaanderen.be/ns/verkeersmetingen#Verkeersmetingverzameling
            delimiter: "/"
            # TODO: user the following when property paths are available for date-observed-property
            # date-observed-property: "[ http://def.isotc211.org/iso19156/2011/CountObservation#OM_CountObservation.phenomenonTime http://www.w3.org/2006/time#hasBeginning http://www.w3.org/2006/time#inXSDDateTimeStamp ]"
            # meanwhile use the following workaround: add http://www.w3.org/ns/prov#generatedAtTime in the "meting-to-oslo.rq" and use it as date-observed-property
            date-observed-property: http://www.w3.org/ns/prov#generatedAtTime
            generatedAt-property: http://www.w3.org/ns/prov#generatedAtTime
            versionOf-property: http://purl.org/dc/terms/isVersionOf
      outputs:
        - name: be.vlaanderen.informatievlaanderen.ldes.ldio.LdioHttpOut
          config:
            endpoint: http://host.docker.internal:3000/data/observation
            content-type: application/n-quads

