PREFIX :             <https://crowdscan.be/ns/>


CONSTRUCT {
    ?s ?p ?o .
}
WHERE {
    ?s ?p ?o .

    {SELECT ?request
    WHERE {
        ?request a :HttpRequest .
    }}
    FILTER(?s != ?request && !(?p = <http://purl.org/dc/terms/isVersionOf> && regex(str(?o),".*zone.*")))
}